### ISSUE TITLE
Version dependencies

### ISSUE THREAD

**Issue by paulhilbert** [tensor5/haskell-happstack#13]
I tried a
    # pacman -S haskell-happstack/haskell-happstack-server
which resulted in (among several other problems):
    warning: cannot resolve "haskell-exceptions=0.8.0.2_0-80", a dependency of "haskell-happstack-server"
    warning: cannot resolve "haskell-network-uri=2.6.0.3_0-10", a dependency of "haskell-happstack-server"

For these two packages I have versions haskell-exceptions=0.8.0.2_0-81 and haskell-network-uri=2.6.0.3_0-11 from the haskell-core repositories. Now I am an AUR maintainer myself and wanted to know if there is any reason at all to fix version dependencies on *package revisions*. This strikes me as being as far from reasonable as one can get with the archlinux packaging guidelines...

Please don't read this as being offensive - I just still have no idea how to install anything haskell after several years of working with/on archlinux...

**Comment by tensor5** [comment]
The last update of [haskell-core] introduced the new `pandoc` version 1.16 which is incompatible with `gitit` in this repository, that's why I didn't update yet. This is the problem of having two haskell repositories, one depending on another.
I will try and fix it in the next days by pulling a patch from upstream.

**Comment by tensor5** [comment]
Fixed by ac0ce749b294d257030581bc6c869632fb726270.
